
# Nome do Workflow
name: Generate Snake Animation

on:
  # Executa uma vez por dia (às 00:00 UTC)
  schedule:
    - cron: "0 0 * * *"
  # Permite executar manualmente pela aba Actions
  workflow_dispatch:
  # Executa também a cada push para o branch 'main' (bom para testar)
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # --- PASSO 1: Faz o checkout do repositório ---
      - name: Checkout Repository
        uses: actions/checkout@v3

      # --- PASSO 2: Gera as animações da cobra ---
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Seu nome de utilizador do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Ficheiros de saída a serem gerados com diferentes temas
          outputs: |
            # Versão Clássica (Verde sobre Preto)
            dist/github-classic-snake.svg?color_snake=green&color_dots=#c6e48b,#7bc96f,#239a3b,#196127&color_bg=#0d1117
            
            # Outras versões que você pode querer usar no futuro
            dist/github-snake-dark.svg?palette=github-dark
            dist/aurora-snake.svg?color_snake=lime&color_dots=#003b4d,#00536e,#006d92,#0089b9,&color_bg=#0d1117
            dist/ocean-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/blue-snake.svg?color_snake=#007ACC&color_dots=#61dafb,#87ceeb,#add8e6&color_bg=#0d1117
        
        env:
          # É necessário para a action poder aceder às suas contribuições
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # --- PASSO 3: Faz o deploy dos ficheiros gerados para o branch 'output' ---
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output # O nome do branch onde as imagens serão guardadas
          commit_message: "chore: update snake animation"
